displayName=Always Walk Here
author=cubeee
description=Select tiles where "Walk here" will always be the top option
tags=
version=1.0.0
plugins=com.github.cubeee.alwayswalkhere.AlwaysWalkHerePlugin
build=standard
